server:
  port: 9091

spring:
  application:
    name: springcloud-eureka-demo-replicas
  security:
    user:
      name: demo
      password: demo123456

eureka:
  instance:
    hostname: eureka-a.scdemo.com
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://demo:demo123456@eureka-b.scdemo.com:9092/eureka, http://demo:demo123456@eureka-c.scdemo.com:9093/eureka
      register-with-eureka: true
      fetch-registry: true
